config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :bookmarks
  resources :categories
  resources :kinds
  get '/api', to: 'api#api'
  get '/api/:id', to: 'api#apiID'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    has_many :bookmark_categories, dependent: :destroy
    has_many :categories, through: :bookmark_categories

    has_many :bookmark_kinds, dependent: :destroy
    has_many :kinds, through: :bookmark_kinds
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[ show edit update destroy ]

  # GET /bookmarks or /bookmarks.json
  def index
    @bookmarks = Bookmark.all
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1 or /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks or /bookmarks.json
  def create
    @bookmark = Bookmark.new
    @bookmark.title= params[:bookmark][:title]
    @bookmark.url= params[:bookmark][:url]
    @bookmark.category_ids= params[:bookmark][:category_id]
    @bookmark.kind_ids= params[:bookmark][:kind_id]
    @bookmark.save

    params[:bookmark][:category_ids].each do |cID| 
      if cID != ""
        @bookmarkcategory = BookmarkCategory.new
        @bookmarkcategory.category_id= cID
        @bookmarkcategory.bookmark_id = @bookmark.id
        @bookmarkcategory.save
      end 
    end 

    params[:bookmark][:kind_ids].each do |kID| 
      if kID != ""
        @bookmarkcategory = BookmarkKind.new
        @bookmarkcategory.kind_id= kID
        @bookmarkcategory.bookmark_id = @bookmark.id
        @bookmarkcategory.save
      end 
    end 
    
    respond_to do |format|
      if @bookmark.save
        format.js {redirect_to bookmarks_path, notice: "Bookmark was successfully created."  }
        format.html { redirect_to @bookmark, notice: "Bookmark was successfully created." }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1 or /bookmarks/1.json
  def update
    params[:bookmark][:category_ids].each do |cID| 
      if cID != ""
        @bookmarkcategory = BookmarkCategory.new
        @bookmarkcategory.category_id= cID
        @bookmarkcategory.bookmark_id = @bookmark.id
        @bookmarkcategory.save
      end 
    end 

    params[:bookmark][:kind_ids].each do |kID| 
      if kID != ""
        @bookmarkcategory = BookmarkKind.new
        @bookmarkcategory.kind_id= kID
        @bookmarkcategory.bookmark_id = @bookmark.id
        @bookmarkcategory.save
      end 
    end 
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.js  { redirect_to bookmarks_path, notice: "title was successfully created." }
        format.html { redirect_to @bookmark, notice: "Bookmark was successfully updated." }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1 or /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: "Bookmark was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :url, category_id: [], kind_id: [])
    end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_create.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<div>
  <strong>Categories:</strong>
  <ul>
    <% @bookmark.categories.each do |c| %>
      <li><%= c %></li>
    <% end %>
  </ul>
</div>

<div>
  <strong>Kinds:</strong>
  <ul>
    <% @bookmark.kinds.each do |k| %>
      <li><%= k %></li>
    <% end %>
  </ul>
    

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/_edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/_form.html.erb
<%= form_with(model: bookmark, remote: true, :format => 'js') do |form| %>
  <% if bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
        <% bookmark.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>


  <div class="field">
    <%= form.label :category_ids, "Categories:" %>
    <br>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :title do |m| %>
      <div class="checkbox col-sm-6 widthLi">
        <%= m.check_box %> <%= m.text %>
      </div>
    <% end %>
  </div>

<br>
  <div class="field">
    <%= form.label :kind_ids, "Kinds:" %>
    <br>
    <%= form.collection_check_boxes :kind_ids, Kind.all, :id, :title do |n| %>
      <div class="checkbox col-sm-6 widthLi">
        <%= n.check_box %> <%= n.text %>
      </div>
    <% end %>
  </div>
  <br>
  
  <div class="actions">
    <%= form.submit data: {confirm: 'Are you sure?'} %>
  </div>
<% end %>

app/views/bookmarks/_index.html.erb
<% @bookmarks.each do |bookmark| %>
    <tr id="book_<%= bookmark.id %>">
      <tr>
        <td><%= bookmark.title %></td>
        <td><%= bookmark.url %></td>
        <td>
          <ul>
            <% bookmark.categories.each do |c| %>
              <li><%= c %></li>
            <% end %>
          </ul>
        </td>
        <td>
          <ul>
            <% bookmark.kinds.each do |k| %>
              <li><%= k  %></li>
            <% end %>
          </ul>
        </td>
        <td><%= link_to 'Show', bookmark, remote: true %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark), remote: true %></td>
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
<% end %>

app/views/bookmarks/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<div>
  <strong>Categories:</strong>
  <ul>
    <% @bookmark.categories.each do |c| %>
      <li><%= c %></li>
    <% end %>
  </ul>
</div>

<div>
  <strong>Kinds:</strong>
  <ul>
    <% @bookmark.kinds.each do |k| %>
      <li><%= k %></li>
    <% end %>
  </ul>
    

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/create.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<div>
  <strong>Categories:</strong>
  <ul>
    <% @bookmark.categories.each do |c| %>
      <li><%= c %></li>
    <% end %>
  </ul>
</div>

<div>
  <strong>Kinds:</strong>
  <ul>
    <% @bookmark.kinds.each do |k| %>
      <li><%= k %></li>
    <% end %>
  </ul>
    

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/create.js.erb
$("#bookmarks-list").append("<%= escape_javascript(render @bookmark, locals: { bookmark: @bookmark} ) %>"​)

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/edit.js.erb
$("#bookmark_edit").empty()
$("#bookmark_edit").append("<%= escape_javascript(render partial: 'bookmarks/edit', locals: { bookmark: @bookmark } ) %>")

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookmarks</h1>
<div id="bookmark_show"></div>
<div class="pb-4" id="bookmark_edit">
  <%= render "form", bookmark: @bookmark %>
</div>

<table class="table ">
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Categories</th>
      <th>Kinds</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="bookmarks-list">
    <%= render 'index' %>
  </tbody>
</table>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.js.erb
$("#bookmark_show").append("<%= escape_javascript(render partial: 'bookmarks/show', locals: { bookmark: @bookmark } ) %>")

app/views/bookmarks/update.js.erb
$(​"#book_<%= @bookmark.id%>"​).html(​ "<%= escape_javascript(render @bookmark, locals: { bookmark: @bookmark} ) %>"​ );